# See https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.9"

services:
  proto:
    container_name: proto
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ./src:/go/src
    tty: true